### ISSUE TITLE
Required packages should include ifensalve and vlan.

### ISSUE THREAD

**Issue by timolow** [rpcdocs/docs-issues#1]
This page http://docs-internal.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec-hosts-target-add.html needs to be updated to include the following packages and instructions:

ifenslave-2.4 and vlan  packages need to be installed and modules “vlan and 8021q” need to be inserted into /etc/modules.

This should be updated to reflect deployment host being merged into infra1 or requirements.txt should include the above needed packaged and updated diagram to reflect nics connecting into container network: http://docs-internal.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec_overview_host-layout.html

**Comment by ionosphere80** [comment]
@timolow, not all installations (including outside of Rackspace after moving to Stackforge) will combine the deployment host with a target host. I think the original plan involved one deployment host managing multiple installations. The installation guide provides instructions for separate hosts, but mentions that you can (easily) consolidate the functions onto a single host such as infra1. If you think it should only cover the latter, we need to bring this issue up for discussion with the development team.

**Comment by darrenchan** [comment]
If there are no further comments or requests, can we close this issue?

**Comment by timolow** [comment]
Im satisfied if we close the issue now.
