### ISSUE TITLE
F5-Specific Pieces of "Post-upgrade Operations" are Impractical for Rackspace Upgrades

### ISSUE THREAD

**Issue by seancarlisle** [rpcdocs/docs-issues#100]
The F5-specific pieces in RPC V11 - RPC V11 Release Notes - Post-upgrade Operations are impractical from a maintenance-centric perspective.  I'm opening this to start a discussion around improving this section.  Running a newly generated F5 config script will fail as it has commands to create pools that already exist.  It would be better to hand NetSec the exact changes they need to make on the F5.  I'm working on getting those together.  This would include the Horizon and Keystone check changes.

Thanks,

Sean

**Comment by klevenstein** [comment]
cc: @b3rnard0 - something for the next bug triage?

**Comment by seancarlisle** [comment]
For reference, most of the F5 bits are here:

http://docs-internal.rackspace.com/rpc/api/v11/bk-rpc-releasenotes/content/upgrade-post-operations.html#rename-f5-monitor

The Keystone bit I'm referring to can be found here:

http://docs-internal.rackspace.com/rpc/api/v11/bk-rpc-releasenotes/content/prereq-v10-v11-keystone.html

**Comment by ckent99999** [comment]
The f5 script as it is now, considers a empty RPC configuration.  The script "creates" items such as nodes, pools, virtual etc.  Re-running the script against a f5 that is already configured would result in syntax errors since the items being created already exist in the same administrative partition.  The configuration would need to be fully wiped and re-added if we wanted to re-run the script.  However, since the same inventory is used, we recommend making just a few delta changes required for the migration.

Most of these changes have to do with monitors (f5 health checks).  It seems unnecessarly risky to rebuild an f5 config for just a few monitor updates.

Jonathan

**Comment by ckent99999** [comment]
The f5 script as it is now, considers a empty RPC configuration.  The script “creates” items such as nodes, pools, virtual etc.  Re-running the script against a f5 that is already configured would result in syntax errors since the items being created already exist in the same administrative partition.  The configuration would need to be fully wiped and re-added if we wanted to re-run the script.  However, since the same inventory is used, we recommend making just a few delta changes required for the migration.

Most of these changes have to do with monitors (f5 health checks).  It seems unnecessarly risky to rebuild an f5 config for just a few monitor updates.
Jonathan

**Comment by klevenstein** [comment]
@seancarlisle @ckent99999 We've opened a bug in rpc-openstack to work on this on the programmatic side: https://github.com/rcbops/rpc-openstack/issues/482

In the meantime, can you let us know what we should put in the docs as a workaround, once you've gotten together the NetSec info? Thanks!

**Comment by ckent99999** [comment]
Working on it now.  I have most of it. I'll run it by the network team for review.

**Comment by ckent99999** [comment]
Not yet fully tested, but here are the recommendations thus far.  I broke them up as "Pre Upgrade" and "Post Upgrade"

#############################
#####   PRE  Upgrade   ######
#############################

### CREATE NEW EXTERNAL MONITOR for KILO ###
   --> Upload !!KILO!! External monitor file to disk.  This is a different monitor than ones used for Juno <--
       run util bash
       cd /config/monitors/
       vi RPC-MON-EXT-ENDPOINT-KILO.monitor
   --> Copy and Paste the External monitor into vi <--
   --> Make sure proper variables are set in the monitors, such as admin username/password and tenant ID <--
       create sys file external-monitor /RPC/RPC-MON-EXT-ENDPOINT-KILO source-path file:///config/monitors/RPC-MON-EXT-ENDPOINT-KILO.monitor
       save sys config
       create ltm monitor external /RPC/RPC-MON-EXT-ENDPOINT-KILO interval 20 timeout 61 run /RPC/RPC-MON-EXT-ENDPOINT-KILO
### END NEW CREATE EXTERNAL MONITOR for KILO ###

### Temporarly update pools to TCP monitor ###
modify ltm pool /RPC/RPC_POOL_CINDER_API { monitor tcp }
modify ltm pool /RPC/RPC_POOL_NOVA_API_OS_COMPUTE { monitor tcp }
modify ltm pool /RPC/RPC_POOL_NEUTRON_SERVER { monitor tcp }
modify ltm pool /RPC/RPC_POOL_KEYSTONE_SERVICE { monitor tcp }
modify ltm pool /RPC/RPC_POOL_GLANCE_API { monitor tcp }
modify ltm pool /RPC/RPC_POOL_GLANCE_REGISTRY { monitor tcp }
modify ltm pool /RPC/RPC_POOL_HEAT_API { monitor tcp }
modify ltm pool /RPC//RPC/RPC_POOL_GALERA { monitor tcp }
### END Temporarly update Monitors to TCP ###

#############################
#####   POST Upgrade   ######
#############################

### Update Monitors ###
modify ltm monitor https /RPC/RPC_MON_HTTPS_HORIZON_SSL { send "HEAD /auth/login/ HTTP/1.1\r\nHost: rpc\r\n\r\n" }
modify ltm monitor http /RPC/RPC_MON_HTTP_NOVA_SPICE_CONSOLE { send "HEAD /spice_auto.html HTTP/1.1\r\nHost: rpc\r\n\r\n" }
modify ltm monitor mysql /RPC/ RPC_MON_GALERA { username monitoring }
### End Update Monitors ###

### Restore pools to proper monitors ###
modify ltm pool /RPC/RPC_POOL_CINDER_API { monitor RPC-MON-EXT-ENDPOINT }
modify ltm pool /RPC/RPC_POOL_NOVA_API_OS_COMPUTE { monitor RPC-MON-EXT-ENDPOINT }
modify ltm pool /RPC/RPC_POOL_NEUTRON_SERVER { monitor RPC-MON-EXT-ENDPOINT }
modify ltm pool /RPC/RPC_POOL_KEYSTONE_SERVICE { monitor RPC-MON-EXT-ENDPOINT }
modify ltm pool /RPC/RPC_POOL_GLANCE_API { monitor RPC-MON-EXT-ENDPOINT }
modify ltm pool /RPC/RPC_POOL_GLANCE_REGISTRY { monitor RPC-MON-EXT-ENDPOINT }
modify ltm pool /RPC/RPC_POOL_HEAT_API { monitor RPC-MON-EXT-ENDPOINT }
modify ltm pool /RPC/RPC_POOL_GALERA { monitor /RPC/RPC_MON_GALERA }
### END Restore pools to proper monitors ###

**Comment by darrenchan** [comment]
Hi @ckent99999,
Thanks for the information. I'm drafting a patch for this, but don't quite understand these two parts when creating an external monitor:
1. create sys file external-monitor /RPC/RPC-MON-EXT-ENDPOINT-KILO source-path file:///config/monitors/RPC-MON-EXT-ENDPOINT-KILO.monitor
2. create ltm monitor external /RPC/RPC-MON-EXT-ENDPOINT-KILO interval 20 timeout 61 run /RPC/RPC-MON-EXT-ENDPOINT-KILO
 
Can you elaborate? Thanks!

**Comment by darrenchan** [comment]
@ckent99999 Just wondering where do you source the external monitor file from?

**Comment by robb-romans** [comment]
Question on IRC from @BjoernT:
Hey quick question, the f5 upgrade script (juno to kilo) is not yet documented?
There's a script which  create additional F5 changes just for the upgrade so we don't have to reinstall the whole F5 config.

**Comment by d34dh0r53** [comment]
Can someone verify that https://github.com/rcbops/rpc-openstack/issues/827 addresses this issue?

**Comment by BjoernT** [comment]
Yes we can close this since https://github.com/rcbops/rpc-openstack/pull/827 will fix it

**Comment by klevenstein** [comment]
Closing. Thanks for the feedback.
