### ISSUE TITLE
Add documentation for console selection in Kilo+

### ISSUE THREAD

**Issue by cfarquhar** [rpcdocs/docs-issues#101]
We can now choose between SPICE and NoVNC consoles.  We'll need to add documentation on:

1. How to select NoVNC or SPICE.
2. How to switch from one to the other.

[1] https://review.openstack.org/#/c/232657
[2] https://bugs.launchpad.net/openstack-ansible/trunk/+bug/1428833

**Comment by klevenstein** [comment]
Closing, reopening as https://github.com/rpcdocs/rpcdocs/issues/457
