### ISSUE TITLE
Incorrect Location for Configuring Horizon SSL

### ISSUE THREAD

**Issue by seancarlisle** [rpcdocs/docs-issues#102]
RPC Installation Guide, RPC v11 (November 13, 2015), 5.14 Configuring Dashboard SSL

The location of the os-horizon role is incorrect:

Currently:
play-books/roles/os-horizon/defaults.main.yml.

Actual:
playbooks/roles/os_horizon/defaults/main.yml

**Comment by erikmwilson** [comment]
Fixed in https://github.com/rpcdocs/rpcdocs/pull/416
