### ISSUE TITLE
Incorrect Playbook References for Adding Compute Node

### ISSUE THREAD

**Issue by seancarlisle** [rpcdocs/docs-issues#103]
RPC Installation Guide RPC v1 (November 13, 2015), 8.4 Adding a compute host

The current line for adding a new compute node is incorrect. setup-everything.yml will eventually call the os-nova-install.yml playbook in setup-openstack.yml, which must be run on all hosts in order for the nova_pubkey attribute to be created properly during the run. Also, the rsyslog-config.yml playbook no longer exists in r11 as the compute nodes no longer have an rsyslog container running on them.

To minimize disruption to existing nodes, the playbooks should be run in the following manner:

openstack-ansible setup-hosts.yml --limit NEW_HOST_NAME
openstack-ansible os-nova-install.yml --limit NEW_HOST_NAME --skip-tags nova-key-distribute
openstack-ansible os-nova-install.yml --tags nova-key-create,nova-key-distribute
openstack-ansible os-neutron-install.yml --limit NEW_HOST_NAME

**Comment by byronmccollum** [comment]
Probably want to ensure hosts files get updated across all compute hosts as well, or instance migration might not function properly.

**Comment by asettle** [comment]
This has been done, and merged. Thank you - closing. 

@byronmccollum if you have anything you'd like added please report in: https://github.com/rpcdocs/rpcdocs/issues
