### ISSUE TITLE
Interface references for networking config

### ISSUE THREAD

**Issue by sigmavirus24** [rpcdocs/docs-issues#11]
Originally created by @pmesserli on 2014-11-05 20:29:41+00:00
----
I noticed that looking in the docs primarily in the 4.6 section that the bond0 and bond1 reference the interfaces for these bonds are all on the same card.  They reference as bond0 being on eth0 and eth2, and bond1 being on eth1 and eth3.  The bonds should span multiple cards for HA purposes, so we do not lose connectivity if a nic card dies.  With the eth format they would be eth0 and eth4, and eth1 and eth5.  

They should also be referencing the new format for nic cards with p6p1 and p7p1 making up bond0 and p6p2 and p7p2 making up bond1.  The new p format for interfaces implies the PCI bus id, and the port number with 1 being the first port on the card.

So it should look like:

auto p6p1
iface p6p1 inet manual
     bond-master bond0

auto p7p1
iface p7p1 inet manual
     bond-master bond0

auto bond0
iface bond0 inet static
     bond-mode active-backup
     bond-miimon 100
     slaves p6p1 p7p1
     address <address>
     netmask <netmask>
     gateway <gateway>
     bond-downdelay 200
     bond-updelay 200
     dns-nameservers 173.203.4.8 173.203.4.9
     dns-search domain

auto p6p2
iface p6p2 inet manual
     bond-master bond1

auto p7p2
iface p7p2 inet manual
     bond-master bond1

auto bond1
iface bond1 inet manual
     up ip link set $IFACE up
     down ip link set $IFACE down
     bond-downdelay 250
     bond-updelay 250
     bond-mode active-backup
     bond-miimon 100
     slaves p6p2 p7p2

The interfaces for service net will not be on the add on cards typically, so these interfaces will appear as emX.  In most cases it will be em3.

auto em3
iface em3 inet static
	address <address>
	netmask <netmask>
	up ip route add 10.191.192.0/18 via 10.144.152.65

-Phil

**Comment by pmesserli** [comment]
Hello Karin! 

I apologize for the delay in response, this should be good now.

Thanks!
