### ISSUE TITLE
How-to use logging tools

### ISSUE THREAD

**Issue by sigmavirus24** [rpcdocs/docs-issues#12]
Originally created by @Bumblebee-Man on 2014-10-23 16:12:07+00:00
----
Would be nice to have documents on how to use the logging tools included with RPC9. 
- What tools are available
- Examples
- Tips and Tricks
- Short cuts 

Why is this needed? While investigating a customer issue I’ve spent more time learning the tools than troubleshooting the issue.

**Comment by klevenstein** [comment]
https://github.com/rcbops/u-suk-dev/issues/70
https://github.com/rcbops/u-suk-dev/issues/69
