### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by sigmavirus24** [rpcdocs/docs-issues#13]
Originally created by @ionosphere80 on 2014-09-23 16:59:23+00:00
----
Backups

(This can wait until after GA from my understanding)

Someone will have to make this all proper.

Here's a rough overview of the backup strategy in 9.0.

Each container has a /var/backup directory that bind mounted out to the host machine in /openstack/backup/<container_name>

Going forward, we should recommend to CDC people that whatever backup software they use, they should be backup up /openstack/backup/*, /opt (for the git cloned ansible files), and /etc (where /etc/rpc_deploy config files live).

On the Galera containers, Holland Xtrabackup has a nightly cron task that will backup the database to /openstack/backup/<galera_container_name>, placing backups in date-named directories.

It is likely that when we determine more things in the product that we want to backup, we will just have the containers write to /var/backup, which is /openstack/backup/<container_name> on the hosts, which gets backed up.

Note: In RDC installs, due to licensing, only infra1 and it's /openstack/backup is getting backed up at this time.

**Comment by RobinJoe** [comment]
One question: does the internal facing document in V9 cover the information for this issue? https://github.com/rpcdocs/v9/blob/master/rpc-v9-installation/src/docbkx/ch-backups.xml

**Comment by RobinJoe** [comment]
I checked in with @ionosphere80 on this issue. There have not been any requests for more backup information since the v9 release, and v9 is entirely outdated. Closing this issue as a result.
