### ISSUE TITLE
Swift Install Guide drive/mount_point confusion

### ISSUE THREAD

**Issue by odyssey4me** [rpcdocs/docs-issues#14]
In the Swift Install Guide, Chapter 4 (or anything else in the guide) didn't make it clear enough to me that, if we use an example of a drive for swift being mounted at ```/srv/swift1```, then the configuration values would be:

```yaml
mount_point: /srv
drives:
    - name: swift1
```

The current documentation made me think that the drive named should be the device values and the mount_point had me lost without getting clarification.

**Comment by erikmwilson** [comment]
So in your example, the name of device sdc is "drive1"?

**Comment by ionosphere80** [comment]
Linux separates device/partition names from mount points. You can mount /dev/sda1 as /mnt/sda1 or /mnt/disk1. The former provides more insight to the actual device/partition name without running 'mount' or looking at the /etc/fstab file. For clarity, the documentation should use the same name for the device/partition and mount point. On a somewhat related note, most of the upstream swift documentation assumes /srv/node as the parent directory for mount points. I'm curious why our configuration defaults to /mnt.

**Comment by erikmwilson** [comment]
I updated the Configure and mount storage devices chapter. Please take a look and let me know if it needs any more clarification.

**Comment by ionosphere80** [comment]
Why isn't the PR tagged here?

**Comment by erikmwilson** [comment]
https://github.com/rpcdocs/v10/pull/58

**Comment by klevenstein** [comment]
Closing this, since it appears to be resolved. Reopen if any further work needs to be done.
