### ISSUE TITLE
Adding a host to an existing environment

### ISSUE THREAD

**Issue by SamYaple** [rpcdocs/docs-issues#15]
Currently I cannot find any documentation on adding a new compute or infra node to an existing environment.

Here are some IRC logs for reference.

15:37 < SamYaple> question for you guys. When adding a new compute node to an existing running deployment, are we creating a limited inventory for that particular node and then running the add_node playbook?
15:38 <@cloudnull> SamYaple: yes. you should append the new compute node the rpc_user_config.yml file and then run the add-node playbook.
15:39 < SamYaple> hmm does that mean restart-containers will run across all of the hosts?
15:42 < hughsaunders> SamYaple: not for adding nodes (that I'm aware of). but restart-containers targets host_group, so you can specify that with -e

**Comment by darrenchan** [comment]
Followed up on email. @cloudnull will provide more details.

**Comment by ionosphere80** [comment]
I spoke to @cloudnull about this procedure and came up with the following:

1) Configure the new compute node using the target host documentation.
2) In the 'rpc_user_config.yml" file, add the new compute node to the 'compute_hosts' stanza. If necessary, also update the 'used_ips' stanza.
3) Run 'ansible-playbook -e @/etc/rpc_deploy/user_variables.yml playbooks/add_host.yml' to add the host and prepare it for OpenStack services.
4) Run 'ansible-playbook -e @/etc/rpc_deploy/user_variables.yml playbooks/openstack/nova-all.yml' to install the nova compute service on the host.
5) Run 'ansible-playbook ansible-playbook -e @/etc/rpc_deploy/user_variables.yml playbooks/infrastructure/rsyslog-config.yml" to configure logging on the host.
6) ???
7) Profit!

**Comment by ionosphere80** [comment]
Also, should this content go into the installation guide, wait for the user guide, or... ?

**Comment by klevenstein** [comment]
Let's doc it in the installation guide for now, but at some point we'll migrate it to the user guide.
Not the prettiest solution, but there is clearly a need in the short term.
