### ISSUE TITLE
additional play for setting up monitoring

### ISSUE THREAD

**Issue by mancdaz** [rpcdocs/docs-issues#16]
This change:

https://review.openstack.org/#/c/145527/

Introduces a new playbook to add a remote check/alarm for ssl certificate expiry, for when the user is using an ssl cert on the load balancer. The following page needs to have an extra section:

http://docs.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec-monitoring-playbooks.html

Something like:

5 (optional) Set up the remote check for ssl certificate expiry:

```
ansible-playbook -e @/etc/rpc_deploy/user_variables.yml playbooks/monitoring/maas_ssl_check.yml
```

**Comment by ionosphere80** [comment]
Does this apply to v9, v10, or both?

**Comment by mancdaz** [comment]
@ionosphere80 at the moment, just v10.
