### ISSUE TITLE
Docs referencing rcbops and not stackforge

### ISSUE THREAD

**Issue by Bumblebee-Man** [rpcdocs/docs-issues#17]
Install Guide, v9, 3.2, URL referenced for downloading is:
git clone -b 9.0.3 https://github.com/rcbops/ansible-lxc-rpc.git
 
Should be: https://github.com/stackforge/os-ansible-deployment.git

**Comment by ionosphere80** [comment]
This also impacts other locations in the installation guide.

**Comment by klevenstein** [comment]
Fix published.
