### ISSUE TITLE
NFS client configuration updates for RPC9

### ISSUE THREAD

**Issue by miguelgrinberg** [rpcdocs/docs-issues#18]
When/if https://review.openstack.org/#/c/145817/ merges, the documentation changes for NFS client configuration need to be backported to RPC9.

**Comment by darrenchan** [comment]
@miguelgrinberg can you elaborate on the changes? I assume we'll need to update http://docs.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec_configure-cinder-nfs.html

**Comment by miguelgrinberg** [comment]
@darrenchan looks like the docs are already updated for this, the page you linked has updated configuration that we backported from v10.

**Comment by darrenchan** [comment]
Thanks @miguelgrinberg.
