### ISSUE TITLE
Remove software installation after launchpad 1400424 fixed

### ISSUE THREAD

**Issue by sigmavirus24** [rpcdocs/docs-issues#2]
Originally created by @BjoernT on 2014-12-08 17:54:56+00:00
----
Please remove the host software installation chapter after launchpad 1400424 has been fixed and made available. Background :

https://bugs.launchpad.net/openstack-ansible/+bug/1400424

**Comment by darrenchan** [comment]
@BjoernT any further comments?

**Comment by BjoernT** [comment]
@darrenchan  The issues was closed as invalid, although we still encounter those issue that certain packages are missing like vlan, ifenslave for instance, prior to running ansible. At the very least the documentation should always assume the installation is based on a minimal image. That means we should mention all packages needed past the minimal install to get ansible in a running state
