### ISSUE TITLE
Remove software installation after launchpad 1400424 fixed

### ISSUE THREAD

**Issue by b3rnard0** [rpcdocs/docs-issues#21]
Issue from the old repo: https://github.com/rcbops/privatecloud-docs/issues/774

From @BjoernT :

>Please remove the host software installation chapter after launchpad 1400424 has been fixed and made available. Background :

>https://bugs.launchpad.net/openstack-ansible/+bug/1400424

**Comment by klevenstein** [comment]
Duplicates #2

**Comment by b3rnard0** [comment]
Duh. Helps to see the entire list of issues.
