### ISSUE TITLE
Rackspace Private Cloud Object Storage Deployment  - RPC v10.1.0, Section 5, "Configure an object storage deployment": Assumes user already has an rpc deployment?

### ISSUE THREAD

**Issue by toxick** [rpcdocs/docs-issues#25]
Documentation apparently assumes user is adding swift onto an existing rpc deployment?  There is no mention in the documentation of gitting the repo or what to do with it after it's got.  Document just assumes all the files already exist where they should be.

**Comment by klevenstein** [comment]
Since there isn't a standalone RPC Swift, we did assume in the Swift guide that there would already be an RPC v10 in place. We should state that as a clear prerequisite.

**Comment by erikmwilson** [comment]
We now have a note in the Overview:
Note
Before installing Object Storage v 2.2.0, OpenStack v10 (Juno) must be installed as Object Storage integrates with some components from the v10 release of OpenStack (for example, keystone, keystone v3).
And an entry in the System Requirements:
Software - Rackspace Private Cloud Object Storage requires OpenStack v10 Software (Juno).

**Comment by klevenstein** [comment]
Might also want to add the note at the beginning of the install procedure, just to make sure we have all the bases covered.

**Comment by erikmwilson** [comment]
Added the following to the Run playbooks section:
Before running the Object Storage playbooks, Rackspace Private Cloud v10 must be installed. Refer to the Rackspace Private Cloud v10 Installation Guide for instructions.

**Comment by erikmwilson** [comment]
Did we cover enough sections to close this issue?

**Comment by klevenstein** [comment]
LGTM. Closing this.
