### ISSUE TITLE
Install Guide, v9 & v10 - need to run rsyslog-config play after all other plays

### ISSUE THREAD

**Issue by odyssey4me** [rpcdocs/docs-issues#26]
Currently the install guides only cover running the host-setup, infrastructure-setup, openstack-setup and optionally the swift-all plays. An additional step needs to be included to finalise the installation - to run the rsyslog-config play.

This goes to each rsyslog container on the hosts and re-generates the rsyslog configuration to ensure that all logs are being forwarded to the ELK stack. If this isn't done then the logs going through to the ELK stack will only be a subset and therefore the ELK stack won't be of much use.

**Comment by ionosphere80** [comment]
The openstack-setup playbook already calls the infrastructure/rsyslog-config playbook... essentially the last playbook unless the user installs swift. The swift-all playbook doesn't include the rsyslog-config playbook.

**Comment by odyssey4me** [comment]
@ionosphere80 Fair enough, in that case I think that perhaps we should just add it as a final play in the swift-all playbook - no more extra documentation. :)

**Comment by odyssey4me** [comment]
Actually, I've just confirmed with my latest patches into the juno branch that it all works without any extras required. Sorry about the incorrect doc issue. :(
