### ISSUE TITLE
Clarify what options are required/optional for swift configuration

### ISSUE THREAD

**Issue by ionosphere80** [rpcdocs/docs-issues#28]
Upstream bug from @nrb :

https://bugs.launchpad.net/openstack-ansible/+bug/1416569

**Comment by ionosphere80** [comment]
Given the addition of substantial documentation to the swift.yml file, I suggest we make a note in the installation guide that references it for details about configuration options including required/optional flags.

**Comment by klevenstein** [comment]
Since we've added the swift example yml file to the swift guide and now refer the reader to it, closing this issue.
