### ISSUE TITLE
Add specific version requirement for pip

### ISSUE THREAD

**Issue by ionosphere80** [rpcdocs/docs-issues#30]
In the installation guide for v9 and v10, add specific version requirement for pip 1.5.6 on deployment and target hosts.

https://bugs.launchpad.net/openstack-ansible/+bug/1418320

**Comment by ionosphere80** [comment]
Parent issue changed from critical to wishlist importance.

**Comment by klevenstein** [comment]
Addressed in: 
https://github.com/rpcdocs/v9/pull/39
https://github.com/rpcdocs/v10/pull/109
