### ISSUE TITLE
Additional info for the Upgrade chapter

### ISSUE THREAD

**Issue by klevenstein** [rpcdocs/docs-issues#32]
Via @BjoernT, from email:

> At least there is the information missing how to generate a hash for horizon_secret_key variable, something which was added to the playbooks recently.

> Additionally I would add at least a mysqldump/hotcopy/xtrabackup for the database for those customers not having a backup  in place..

> Also I think we are currently working on documentation for the eventlet library downgrade and I wrote documentation to downgrade oslo.messaging. But those steps apply for certain releases only like 9.0.6

**Comment by sigmavirus24** [comment]
> At least there is the information missing how to generate a hash for horizon_secret_key variable, something which was added to the playbooks recently.

This was added in November or December. I think running the script to generate new secrets/passwords/etc. will find this and generate it without changing existing passwords. I'm not sure if it knows to add this if it isn't already in the file though. So it may be necessary to determine what options have been added to user variables/etc. and have a nice way of adding those to the existing file before regenerating. @cloudnull or @d34dh0r53 may be better equipped to answer that.

> Also I think we are currently working on documentation for the eventlet library downgrade and I wrote documentation to downgrade oslo.messaging.

Note this is only for v10. v9 has a working version of oslo.messaging that does not contain the bug @BjoernT is mentioning.

**Comment by ionosphere80** [comment]
@BjoernT The upgrade content already mentions performing a backup prior to upgrading.

**Comment by BjoernT** [comment]
@sigmavirus24 
9.0.5 is affected of oslo.messaging which we downgrade/pin in 9.0.6
9.0.6 is affected from eventlet issues, that's why 9.0.7 has been created
