### ISSUE TITLE
SOFTWARE RELEASE NOTES, V10, Chapter 4, "Changed features: v9 to v10": Broken link Installation Guide

### ISSUE THREAD

**Issue by IRTermite** [rpcdocs/docs-issues#34]
http://docs-staging.rackspace.com/rpc/api/v10/bk-rpc-v10-releasenotes/content/rpc-upgrade-v9-10.html

New: Block storage availability zones

To enable this feature, see the <Installation Guide>.  <- Link broken 404

**Comment by ionosphere80** [comment]
External links to v10 documentation will 404 until we publish it to the public on docs.rackspace.com.
