### ISSUE TITLE
Missing "python" in front of script 

### ISSUE THREAD

**Issue by ihavegerms** [rpcdocs/docs-issues#35]
Reference Page: http://docs-staging.rackspace.com/rpc/api/v10/bk-rpc-installation/content/sec_configure-passwords.html

The code section says to do the following;
cd /opt/os-ansible-deployment/scripts
pw-token-gen.py --file /etc/rpc_deploy/user_variables.yml

the second line should be changed to;

python pw-token-gen.py --file /etc/rpc_deploy/user_variables.yml

**Comment by ihavegerms** [comment]
I'm really sorry for the bold 25+ font... not sure what that was about... it definitely wasn't intended.

**Comment by klevenstein** [comment]
Markdown fun. There was a `#` copied over (the command line prompt) and markdown interprets that character as "The rest of this line is a HEADING 1"

**Comment by ihavegerms** [comment]
Hah, good times. Nice catch.
