### ISSUE TITLE
glance_swift_enable_snet information can be removed

### ISSUE THREAD

**Issue by BjoernT** [rpcdocs/docs-issues#38]
In bk-rpc-installation/content/sec_configure-glance.html it says:
====
In Rackspace datacenters, optionally enable the service network:

glance_swift_enable_snet: True
===
This configuration is actually not used so it can be removed from the documents. Per devs, this will also not be used in the future

**Comment by odyssey4me** [comment]
It is still there for 9 and 10. For 11 it may still be used, but via a slightly different mechanism (RPC-extras).

**Comment by BjoernT** [comment]
I just searched the RPC9 & 10 playbooks and roles and it is not used anywhere

**Comment by klevenstein** [comment]
Closed in rpcdocs/v10#137
