### ISSUE TITLE
Pre patch notes for 9.0.7 and 10.1.2 in regards to keystone token-flush

### ISSUE THREAD

**Issue by BjoernT** [rpcdocs/docs-issues#39]
We need to add additional information in the release notes beginning 9.0.7 and 10.1.2 that prior to the installation, the keystone.token table needs to be cleaned up manually in order to avoid table locks after installing the RPC patches. The is linked to https://bugs.launchpad.net/openstack-ansible/+bug/1410437 which fixed the token-flush call so it will automatically delete all expired tokens from the database.
Since this script never worked in RPC9, long running deployments have accumulated large amounts of expired tokens already. Those need to be cleaned by ideally dropping the keystone.token table and recreating the table.

**Comment by odyssey4me** [comment]
Isn't dropping it a little harsh? Why not truncate it, or just run the tool prior to the update and patiently wait for it to complete?

**Comment by BjoernT** [comment]
Well, the galera replication slows down the truncate that much that it can a) timeout or b) lock the table.
We have deployments with > 1 million rows in that table and were deleting 10k at a time, not to run into a and b. It takes nearly a whole day for one deployment to get rid of all entries. Dropping and recreating is just a blip compared to that.

**Comment by robb-romans** [comment]
@BjoernT @odyssey4me please review, thanks

**Comment by robb-romans** [comment]
@BjoernT Hi Bjorn. Could you please supply the commands to drop and recreate the table? Thanks.
