### ISSUE TITLE
Technical FAQ, v10, 2.1, "Operating system and architecture", Answer to Ansible advantages question

### ISSUE THREAD

**Issue by kencjohnston** [rpcdocs/docs-issues#41]
A: Since RPC uses LXC containers, Chef is a much heavier service than is required. We use Ansible to lay down containers and manage source code installation. Ansible's automation framework is great at orchestrating tasks across multiple hosts. RPC's Ansible deployment process has become the reference Ansible deployment model for OpenStack.

**Comment by klevenstein** [comment]
Fixed in rpcdocs/v10#139
