### ISSUE TITLE
Technical FAQ, v10, 2.3, "Database architecture", Remove duplicate section on scaling

### ISSUE THREAD

**Issue by kencjohnston** [rpcdocs/docs-issues#42]
Q: What are the requirements and restrictions for a MariaDB ....

A: There must be at least three database nodes. RPC architecture has three control plane nodes and deploys one database container on each.

REMOVE: When scaling..... 
As it is repeated in the answer to question "How is the cluster scaled up?"

**Comment by klevenstein** [comment]
Closed: https://github.com/rpcdocs/v10/pull/138
