### ISSUE TITLE
Chapter 4 – Issues states no issues in RPCv10 but few are listed in 7

### ISSUE THREAD

**Issue by BjoernT** [rpcdocs/docs-issues#43]
In chapter 4  – Issues we state there a no known issues but under 7 we actually list few. Can we either remove the issues under 4 or link to 7 ?

**Comment by klevenstein** [comment]
Since that section is specifically referring to issues with the upgrade, we'll change the wording to: "There are no known upgrade issues. For general known issues, refer to...."

**Comment by BjoernT** [comment]
Good that will work. Thanks

**Comment by klevenstein** [comment]
Fixed in rpcdocs/v10#159
