### ISSUE TITLE
Dashboard access 

### ISSUE THREAD

**Issue by darrenchan** [rpcdocs/docs-issues#44]
https://one.rackspace.com/pages/viewpage.action?title=RPC+v9+and+v10+User+Guide&spaceKey=PrivateCloud

From Vinson Rogers:
"The installation guide specifies load balancing VIPs yet the GSG specifies going directly to a controller IP for dashboard access:
http://docs.rackspace.com/rpc/api/v10/bk-rpc-installation/content/sec-playbooks-openstack-verify.html (btw the plus and minus icons on the ToC on the left of this are not working properly on some items)
http://23.253.231.218/rpcdocs/user/v10/content/access-cloud-gui.html"

**Comment by asettle** [comment]
A suggestion to have both instructions in the GSG? Will this mean we will have to update the Install guide too?

@klevenstein you have a note in the Install Guide saying that that section, "Verifying OpenStack operation", needs to be moved to a User Guide. Do you still want this information removed and added into the new User Guide?

**Comment by asettle** [comment]
https://github.com/rpcdocs/v10/pull/182 - fixed. VIP information added to user guide. 
Pending response from Karin regarding her note in the install guide.

**Comment by klevenstein** [comment]
Okay, after some consideration, here's what I think: make "Verifying OpenStack operation" into a standalone common section file and save it in rpc-common, and xi:include it in both the Installation Guide and the User Guide. There are sound arguments for having it in both places and if we do it this way, the overhead is minimal.

**Comment by asettle** [comment]
Will do today, thanks @klevenstein

**Comment by asettle** [comment]
Please see: https://github.com/rpcdocs/v10/pull/185 for the closing of this bug
