### ISSUE TITLE
Nova is no longer used for floating IP management

### ISSUE THREAD

**Issue by darrenchan** [rpcdocs/docs-issues#45]
https://one.rackspace.com/pages/viewpage.action?title=RPC+v9+and+v10+User+Guide&spaceKey=PrivateCloud

Information in GSG Chapter 9 is no longer applicable. Update information.

**Comment by asettle** [comment]
For now I'll remove the information.
@ionosphere80  will hopefully be taking me through the updated networking (neutron/nova) processes soon.

**Comment by asettle** [comment]
https://github.com/rpcdocs/v10/pull/181
