### ISSUE TITLE
Changes to GSG Instances chapter

### ISSUE THREAD

**Issue by darrenchan** [rpcdocs/docs-issues#47]
https://one.rackspace.com/pages/viewpage.action?title=RPC+v9+and+v10+User+Guide&spaceKey=PrivateCloud

From Vinson Rogers:
1. Table 7.1 In the Flavor row, and Details column, change "The vCPU configuration." to include vCPU, Memory and Disk.
2. Update section 7.1  Creating an instance using the command line
"Other sections have the command options listed in a table, could that be added to http://23.253.231.218/rpcdocs/user/v10/content/create-instance-cli.html
 
I also think the example uses some mixed format and potentially old format flags. --flavor="2" can be just --flavor 2 to match the rest of the command options."

**Comment by asettle** [comment]
Updated number 1 (included vCPU, Memory and Disk) - https://github.com/rpcdocs/v10/pull/182

**Comment by asettle** [comment]
@klevenstein is someone working on this? I started, and was drawn away to something else. 
1 - Completed.
2 - This part is particularly unclear, or at least, I'm not seeing any issues with the current version?
3 - Fixed this (please see below)

**Comment by klevenstein** [comment]
If anyone else is, I don't know about it.

**Comment by asettle** [comment]
@klevenstein okay great. I've done what I saw as an issue. Potentially someone look over point 2 there to make sure I haven't misunderstood?

**Comment by asettle** [comment]
Let me know if anyone has an issue with my closing of this bug. My patches are referenced above.
