### ISSUE TITLE
Document RPC Repo playbooks

### ISSUE THREAD

**Issue by sigmavirus24** [rpcdocs/docs-issues#5]
Originally created by @klevenstein on 2014-11-17 20:05:35+00:00
----
Pending:
* when this PR goes through: https://review.openstack.org/#/c/139260/
* whatever release this gets targeted for

> This adds the ability for the user to stand up a repo for all of the python packages that may be needed for a given environment. This will allow a user to maintain their own repo of packages for production purposes in CDC where public internet may not be available or for development purposes.

Kevin's gist here: https://gist.github.com/cloudnull/fbcd4e371216af2fef31

**Comment by darrenchan** [comment]
@klevenstein This change has been abandoned, if I'm reading it correctly?

**Comment by klevenstein** [comment]
Looks like it. Closing for now, leaving instructions to re-open in the event it becomes a thing again.
