### ISSUE TITLE
Old 'ansible-lxc-rpc' repo name referenced

### ISSUE THREAD

**Issue by byronmccollum** [rpcdocs/docs-issues#50]
Object Storage Deployment, v10, 6, "Running Object Storage playbooks"

Step 1 states...

Change to the `~/ansible-lxc-rpc/rpc_deployment` directory.

...but should read...

Change to the `/opt/os-ansible-deployment/rpc_deployment` directory.

**Comment by darrenchan** [comment]
Section 8.2

**Comment by byronmccollum** [comment]
Oops. Should be `/opt/os-ansible-deployment/rpc_deployment`.

**Comment by byronmccollum** [comment]
@darrenchan 

Document: Rackspace Private Cloud Object Storage Deployment (v10)
Section: 6
Heading: Running Object Storage playbooks
Step: 1

**Comment by byronmccollum** [comment]
I guess I could add a URL...

http://docs.rackspace.com/rpc/api/v10/bk-rpc-swift/content/sec-playbooks-foundation-run.html
