### ISSUE TITLE
Add rabbitmq-server downgrade instruction for 9.0.7 or 10.1.2

### ISSUE THREAD

**Issue by BjoernT** [rpcdocs/docs-issues#52]
The new RPC releases "pin" rabbitmq as 3.4.3 version but if customers did install 9.0.6 or 10.1.1 already, the rabbitmq version might have been upgraded to >3.4.3 already

The only solution is to download the desired version and downgrade manually:

- Stop rabbitmq server beginning node 03 down to node 01
        service rabbitmq-server stop

- Downgrade rabbitmq-server
    wget http://www.rabbitmq.com/releases/rabbitmq-server/v3.4.3/rabbitmq-server_3.4.3-1_all.deb && dpkg -i rabbitmq-server_3.4.3-1_all.deb && rm -f rabbitmq-server_3.4.3-1_all.deb

- Start the rabbitmq server beginning in a reversed order from node 01 to node 03

**Comment by robb-romans** [comment]
See also https://github.com/rpcdocs/docs-issues/issues/48

**Comment by robb-romans** [comment]
From @odyssey4me bug comments: "This needs to be listed as a known issue for anything < 9.0.7 and < 10.1.2"

**Comment by darrenchan** [comment]
@odyssey4me  @BjoernT  Can you review the patch? Thanks!

**Comment by klevenstein** [comment]
https://github.com/rpcdocs/v9/pull/51
