### ISSUE TITLE
Add upgrades nodes from 9.0.6 to 10.1.2 to fix horizion permissions prior to the openstack-setup.yml execution

### ISSUE THREAD

**Issue by BjoernT** [rpcdocs/docs-issues#53]
cd /opt/os-ansible-deployment/rpc_deployment
ansible horizon_container -m shell -a 'chown -R www-data:www-data /usr/local/lib/python2.7/dist-packages/openstack_dashboard /usr/local/lib/python2.7/dist-packages/static/horizon /usr/local/lib/python2.7/dist-packages/static/'

**Comment by klevenstein** [comment]
@BjoernT - just sent you an invite that should give you access to the rpcdocs repos to review the patches.

**Comment by BjoernT** [comment]
OK Thanks, I'm checking those updates.

**Comment by klevenstein** [comment]
https://github.com/rpcdocs/v10/pull/195
