### ISSUE TITLE
Add known issues for cinder in a availability zone configuration at RPC 10.1.2

### ISSUE THREAD

**Issue by BjoernT** [rpcdocs/docs-issues#54]
The Cinder.conf default availability zone config name is incorrect.

`cinder_default_availability_zone` should be `default_availability_zone`.

See https://bugs.launchpad.net/openstack-ansible/juno/+bug/1429201

Current solution is only to change fix rpc_deployment/roles/cinder_common/templates/cinder.conf

**Comment by robb-romans** [comment]
Thanks @BjoernT. Please review suggested fix.

**Comment by klevenstein** [comment]
https://github.com/rpcdocs/v10/pull/194
