### ISSUE TITLE
Please add known issue for 10.1.2 and swift documentation

### ISSUE THREAD

**Issue by BjoernT** [rpcdocs/docs-issues#55]
As per https://bugs.launchpad.net/openstack-ansible/+bug/1411465 if the setting replication_network is the same as storage_network, the swift setup will fail. We need to add the information not to configure replication_network if no dedicated replication network exit

**Comment by erikmwilson** [comment]
I added a note to the configure replication network section:

Optionally, specify a dedicated replication network interface, so dedicated replication can be setup. If this value is not specified, no dedicated replication_network is set. 

Note:
If no dedicated replication network exists, do not specify a replication network.
As with the storage_network, if the repl_ip is not set on the replication_network interface, replication will not work properly.

**Comment by erikmwilson** [comment]
You can see the new content here: https://github.com/rpcdocs/v10/pull/203

**Comment by klevenstein** [comment]
Closing, fix merged.
