### ISSUE TITLE
MaaS Docs

### ISSUE THREAD

**Issue by cbruf82** [rpcdocs/docs-issues#56]
The docs are not specifying the session token as the token needed to install maas: (Use the maas-token script to request a MaaS impersonation token. ) This should be replaced with Session Token) Also this should be added to the docs:

Run this from your local machine:

python ./maas-cloud-token.py <yourSSO> <account number>

To be more specific.

In this section: 

maas_auth_method: token
maas_auth_token:IMPERSONATION_TOKEN
maas_api_url: https://monitoring.api.rackspacecloud.com/v1.0/hybrid:CORE_ACCOUNT_ID
maas_fqdn_extension: FQDN_extension
maas_notification_plan: npManaged
maas_repo_version: V.n.n

(maas_auth_token:IMPERSONATION_TOKEN) Should be SESSION_TOKEN

This will make things clearer for people who have not used the MaaS setup before

**Comment by klevenstein** [comment]
Thanks for the info, @cbruf82. Can you review https://github.com/rpcdocs/v9/pull/52 to make sure it's been updated correctly? I've sent you an invite that, once accepted, should give you access to our repos.

**Comment by robb-romans** [comment]
Hi @cbruf82 any comments on https://github.com/rpcdocs/v9/pull/52 ?  Thanks.

**Comment by klevenstein** [comment]
Fix merged; reopen if anything needs updating.
