### ISSUE TITLE
Reword Drive Mount Locations

### ISSUE THREAD

**Issue by seancarlisle** [rpcdocs/docs-issues#57]
Object Storage Deployment, v10, 4.1, "Configuring and mounting storage devices"

Step two where mount locations are specified should be reworded.  The current wording gives the impression that all devices are to be mounted to the same location as opposed to a 1:1 mount point for each drive.  

Also, we should specify the mount options for these drives.  According to  http://docs.openstack.org/developer/swift/deployment_guide.html, we should be mounting these drives with the following options:  noatime, nodiratime, nobarrier, logbufs=8 

and so should be added to /etc/fstab like so:
                         
/dev/sdb   /srv/nodes/sdb   xfs   noatime,nodiratime,nobarrier,logbufs=8   0 0

**Comment by erikmwilson** [comment]
Please review the new content here: https://github.com/rpcdocs/v10/pull/203

**Comment by robb-romans** [comment]
@seancarlisle are the changes made here https://github.com/rpcdocs/v10/pull/203 sufficient to close this issue? Thanks.

**Comment by seancarlisle** [comment]
@robb-romans I get a 404 when clicking that link :(

**Comment by robb-romans** [comment]
@seancarlisle here's a direct link to the commit: "https://github.com/rpcdocs/v10/commit/9da37291e84ad56f52556adad13e5e8823c3316a"

**Comment by klevenstein** [comment]
@seancarlisle I've sent you an invite that, once accepted, should give you access to the repo.

**Comment by robb-romans** [comment]
ah, access issue. thanks @klevenstein

**Comment by seancarlisle** [comment]
I can see the pull request now.  Thanks @klevenstein!

**Comment by seancarlisle** [comment]
@robb-romans There are a couple of things:

1.  In the mkfs example, "-L" is the correct label argument.
   e.g. mkfs.xfs -f -i 1024 -L sdc /dev/sdc
2. In your fstab example, please remove the device names at the beginning of each line (but keep label=sd<whatever>.)  As-is, this will cause errors when the mount command is executed on /etc/fstab.  
   e.g. label=sdc /srv/node/sdc xfs noatime,nodiratime,logbufs=8,noauto 0 0

Hope that helps!

**Comment by seancarlisle** [comment]
Sorry, just realized point 1 should probably go in #49.  Regarding the mount wording, its still a bit confusing.  I think you should bring back the bit about creating the mount directories under one parent directory (/mnt or /srv/nodes), and specify they should be named after respective drive labels.

**Comment by erikmwilson** [comment]
@seancarlisle 
I have updated the doc with both comments - https://github.com/rpcdocs/v10/pull/211. Does there need to be any additional changes?

**Comment by klevenstein** [comment]
Fix merged; closing issue. @seancarlisle please reopen if necessary.

**Comment by erikmwilson** [comment]
Thanks. I've been sending reminder notes every week and getting nothing.
