### ISSUE TITLE
Add steps to use haproxy during deployment and clean up before handover

### ISSUE THREAD

**Issue by cfarquhar** [rpcdocs/docs-issues#61]
In order to speed up the deployment process, we need to use haproxy during the early stages of the deployment.  HAproxy will need to be removed prior to running the MaaS playbooks and the QC process needs to verify it was removed.

Please add the haproxy installation/configuration [1] steps to the beginning of the deployment section and the removal steps [2] before the MaaS installation steps.  Both should only be added to the internal docs.

[1] https://one.rackspace.com/pages/viewpage.action?pageId=115362257#RPC9and10Tips/Tricks/Issues/FAQs-ConfigureHAPRoxyforRPC9andhigher

[2] https://one.rackspace.com/pages/viewpage.action?pageId=110992052#RPC9.x+Post-DeploymentQCProcess%28DRAFT%29-ManualTests

**Comment by klevenstein** [comment]
@darrenchan since I'm making a change that depends on this one, I'll go ahead and take care of this.

**Comment by klevenstein** [comment]
@cfarquhar please review:
http://docs-internal-staging.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec-hosts-haproxy.html
http://docs-internal-staging.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec-environment-haproxy-remove.html

**Comment by robb-romans** [comment]
Hi @cfarquhar. Can this issue be closed? Thanks.

**Comment by klevenstein** [comment]
Fix merged, closing. @cfarquhar please reopen if any further changes are needed.

**Comment by klevenstein** [comment]
Reopening due to comment here:
http://docs-internal.rackspace.com/rpc/api/v10/bk-rpc-installation/content/sec-environment-haproxy-remove.html#2c

Which playbook should be run in step 2? haproxy_install.yml or a different one? It's not entirely clear from the links above.

cc: @cfarquhar

**Comment by claco** [comment]
Paging @sigmavirus24

**Comment by sigmavirus24** [comment]
Huh?

**Comment by klevenstein** [comment]
I think this is resolved? In any case, it's been over a month since the last activity; closing. Reopen if needed, or open a new issue.
