### ISSUE TITLE
RPC MaaS docs update

### ISSUE THREAD

**Issue by klevenstein** [rpcdocs/docs-issues#62]
Details here:
[Trello card](https://trello.com/c/6cjrTamL/30-rackspace-monitoring-agent-logging-buffering-error-does-not-terminate-or-anything-end-result-is-the-agent-is-not-installed)
https://github.com/rcbops/rpc-maas/issues/110

**Comment by klevenstein** [comment]
Dev work in progress (3/24), status TBD

**Comment by robb-romans** [comment]
NB: MaaS playbooks moved to rpc-extras repo. Commit: https://github.com/miguelgrinberg/rpc-extras/commit/4059eb634777b671aae280fb801193e78c0f3b36

**Comment by robb-romans** [comment]
@klevenstein does any work remain to close this issue?

**Comment by klevenstein** [comment]
Not the I know of

**Comment by robb-romans** [comment]
great, closing
