### ISSUE TITLE
Add step to have MBU configure CommVault (internal only, Rackspace DC only)

### ISSUE THREAD

**Issue by cfarquhar** [rpcdocs/docs-issues#63]
https://one.rackspace.com/display/PrivateCloud/RCB+Backups+v9.0

**Comment by klevenstein** [comment]
@cfarquhar We have a line about asking MBU to install the commvault packages:
http://docs-internal.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec-backup-core.html

Is there something more that I'm missing?

**Comment by robb-romans** [comment]
Hi @cfarquhar. Is this proposed fix sufficient to close this issue? Thanks.

**Comment by BjoernT** [comment]
I think it's ok but personally I would the remove the version v9.n.n for example. Also we should point out that we currently do not backup the logging servers or more precise the elasticsearch instance (#https://bugs.launchpad.net/openstack-ansible/+bug/1400440)

**Comment by klevenstein** [comment]
Made updates; closing issue. Reopen if necessary. Thanks!
