### ISSUE TITLE
QC environment (internal only)

### ISSUE THREAD

**Issue by cfarquhar** [rpcdocs/docs-issues#64]
After all playbooks are run, engineers should follow this post-deployment QC process.  Since it's likely to change frequently, I think the docs should simply reference this wiki page.  I'm open to other thoughts though.

https://one.rackspace.com/pages/viewpage.action?pageId=110992052

**Comment by klevenstein** [comment]
@cfarquhar please review:
http://docs-internal-staging.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec-environment-qc.html
http://docs-internal-staging.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec-monitoring-qc.html

**Comment by robb-romans** [comment]
Hi @cfarquhar. Can this issue be closed?

**Comment by klevenstein** [comment]
Closing due to radio silence; reopen if needed.
