### ISSUE TITLE
Add known issue for CentOS 7 or RedHat 7 Guest OS console accessability

### ISSUE THREAD

**Issue by BjoernT** [rpcdocs/docs-issues#65]
We did notice console spice issues even in Linux guests based on RedHat/CentOS version 7 affecting the usability. This issue renders the Openstack console useless for such guests. And I identified a workaround to gain proper access to the console again, without affecting the RPC release cycle.
If the frame buffer mode for the guest console is disabled, the console switches into a text only mode and can be used fully after applying these changes. This issue affects RPC 9 and higher.

====== Instructions for Linux Guests ======
Please add inside the /etc/default/grub config file the 
option "nofb nomodereset" to the GRUB_CMDLINE_LINUX variable and regenerate the grub2 config

Tested config /etc/default/grub
-------------------------------
GRUB_TIMEOUT=1
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL="serial console"
GRUB_SERIAL_COMMAND="serial"
GRUB_CMDLINE_LINUX="console=ttyS0 console=tty0 crashkernel=auto vconsole.keymap=us nofb nomodereset"
GRUB_DISABLE_RECOVERY="true"

Rebuilt grub2 config
--------------------
grub2-mkconfig -o /boot/grub2/grub.cfg

After the mandatory reboot the console will boot in text mode only and not using any frame buffer graphic device.

**Comment by darrenchan** [comment]
@BjoernT is there a link to the launchpad bug?

**Comment by BjoernT** [comment]
@darrenchan It's related to https://bugs.launchpad.net/openstack-ansible/+bug/1428833

**Comment by darrenchan** [comment]
Thanks!

**Comment by robb-romans** [comment]
Hi @BjoernT. Can this issue be closed?
v11 fix: https://github.com/rpcdocs/v11/commit/b186088dd77546a33767d6c54de78939bcb1177a
v10 fix: https://github.com/rpcdocs/v10/commit/b85d88cc828ecafc4f79f39598fe0428ca19a660
v9 fix: https://github.com/rpcdocs/v9/commit/0ef4d3ef28f7ef01dae41a1fe11f5b1d419aaeaf

**Comment by BjoernT** [comment]
@robb-romans  Yes looks good.

**Comment by robb-romans** [comment]
@BjoernT thanks! closing.
