### ISSUE TITLE
Change and updating SPICE console information - User Guide

### ISSUE THREAD

**Issue by RobinJoe** [rpcdocs/docs-issues#66]
The procedure in the user guide needs to be documented correctly. An overide should be used instead of modifying the playbooks. The correct procedure is:

echo 'nova_console_endpoint: 172.29.236.10' >> /etc/rpc_deploy/user_variables.yml
cd /opt/os-ansible-deployment/rpc_deployment && ansible-playbook -e @/etc/rpc_deploy/user_variables.yml playbooks/openstack/nova-all.yml

**Comment by robb-romans** [comment]
Can this issue be closed? Thanks.

**Comment by klevenstein** [comment]
Fix merged; looks closable to me.
