### ISSUE TITLE
Assorted comments from docs-internal

### ISSUE THREAD

**Issue by klevenstein** [rpcdocs/docs-issues#70]
This one is addressed by #69: http://docs-internal.rackspace.com/rpc/api/v10/bk-rpc-installation/content/sec-install-solutions.html#1c

The rest may or may not have been addressed:
http://docs-internal.rackspace.com/rpc/api/v10/bk-rpc-installation/content/sec-install-solutions.html#2c
http://docs-internal.rackspace.com/rpc/api/v10/bk-rpc-installation/content/sec-install-solutions.html#3c
http://docs-internal.rackspace.com/rpc/api/v10/bk-rpc-installation/content/sec-environment-haproxy-remove.html#1c
http://docs-internal.rackspace.com/rpc/api/v10/bk-rpc-installation/content/sec-install-solutions.html#4c

Should we refresh the docs sooner rather than later?

**Comment by robb-romans** [comment]
Will also fix: 

From Hippiepete:
Change
/etc/rpc_deploy/rpc_user-config.yml
to
/etc/rpc_deploy/rpc_user_config.yml
----
Page: http://docs-internal.rackspace.com/rpc/api/v10/bk-rpc-installation/content/sec_cinder-availabilityzones.html#1c
