### ISSUE TITLE
Need to Specify Galera Container in Host Setup for Rebuilding a Container

### ISSUE THREAD

**Issue by seancarlisle** [rpcdocs/docs-issues#72]
Rackspace Private Cloud Installation Guide - RPC, V9.0.7, 10. Operations, "Rebuilding a container": In step 3 you must also specify the galera container name as an additional limit flag, otherwise the host-setup playbook will fail because it can't find the galera container.  The example should be:

```
$ ansible-playbook -e @/root/rpc_deploy/user_variables.yml \
  playbooks/setup/host-setup.yml -l node3 -l node3_galera_container-3ea2cbd3
```

**Comment by darrenchan** [comment]
Does this also apply for v10 and v11?

**Comment by seancarlisle** [comment]
Hi @darrenchan, that is correct.

**Comment by robb-romans** [comment]
fixed in v9 by https://github.com/rpcdocs/v9/commit/7447d4c3e2e77422211912eaa34f62509726829d

**Comment by robb-romans** [comment]
thanks all. v9,v10,v11 updated. closing.
