### ISSUE TITLE
v10.1.x feature backport from v11

### ISSUE THREAD

**Issue by sigmavirus24** [rpcdocs/docs-issues#73]
As part of [this bug](https://bugs.launchpad.net/openstack-ansible/+bug/1439892) we [added an extra user variable](https://github.com/stackforge/os-ansible-deployment/commit/1e27d6735b47107d81d3ef8bf5e7db25bf4f9259) (`glance_flavor`) which is present in Kilo but was not present in Juno. This allows users to choose their Paste Deploy flavor for Glance.

The possible configurable options are:

- (Nothing)
- caching
- cachemanagement
- keystone
- keystone+caching
- keystone+cachemanagement (the default)
- trusted-auth
- trusted-auth+cachemanagement

This is important specifically because with the current container size of Glance, it is possible for Glance to attempt to cache an image which would exceed the available disk space. By selecting an option above that does not involve caching, the user can disable caching altogether. For example, if the user wants to continue to use keystone but doesn't want any caching they would set

```yaml
glance_flavor: keystone
```

Alternatively, if they want an unauthenticated glance that does not perform caching, they should be able to do

```yaml
glance_flavor:
```

**Comment by klevenstein** [comment]
Looks like this will need to be added to the Glance config section:
http://docs-internal.rackspace.com/rpc/api/v10/bk-rpc-installation/content/sec_configure-glance.html

And it applies to v11 too?

**Comment by sigmavirus24** [comment]
Yes. This option was already present. It's not clear to me if this happened when the os-a-d project was de-rax-ified or if it happened since then. But glance_flavor was already a variable before this bug was fixed.

**Comment by robb-romans** [comment]
Hi. I'm confused by "feature backport from v11". I'm probably confused so set me straight. I don't see these new glance variables in master:
https://github.com/stackforge/os-ansible-deployment/blob/master/etc/openstack_deploy/user_variables.yml

I *do* see them in 10.1.4:
https://github.com/stackforge/os-ansible-deployment/blob/10.1.4/etc/rpc_deploy/user_variables.yml

**Comment by sigmavirus24** [comment]
So the variable in v11 is defined as a default [here](https://github.com/stackforge/os-ansible-deployment/blob/master/playbooks/roles/os_glance/defaults/main.yml#L32). The user can override that variable in `/etc/openstack_deploy/user_variables.yml` if I understand correctly.

In v11, a lot of the default values were moved out of `user_variables` into proper defaults files. I think @d34dh0r53 or @cloudnull can both provide more context on that/correct my above statements if they're wrong.

**Comment by robb-romans** [comment]
@sigmavirus24 thanks. please review https://github.com/rpcdocs/rpcdocs/pull/28 for v11. If that's good, I'll go fix v10 also.
