### ISSUE TITLE
add host instructions missing neutron-all playbook information

### ISSUE THREAD

**Issue by robb-romans** [rpcdocs/docs-issues#75]
From @BjoernT 

The add host instructions are missing an important information that the neutron-all playbook has to be run as well. For example http://docs.rackspace.com/rpc/api/v10/bk-rpc-installation/content/sec-operations-add-compute-host.html

we run

ansible-playbook -e @/etc/rpc_deploy/user_variables.yml playbooks/openstack/neutron-all.yml

after nova-all.yml to add the neutron agents onto the new compute node

**Comment by BjoernT** [comment]
I would expect that we have something similar in kilo and have to run os-neutron-install.yml while adding hosts. Maybe we include a dev here

**Comment by robb-romans** [comment]
Looks like our add compute host procedure is out of sync with OSAD master. This needs dev feedback, please:
http://docs-internal-staging.rackspace.com/rpc/api/v11/bk-rpc-installation/content/sec-operations-add-compute-host.html

**Comment by stevelle** [comment]
Steps 1 and 2 are fine.

Step 3 can be:
```bash
cd /opt/os-ansible-deployment/playbooks
openstack-ansible setup-everything.yml rsyslog-config.yml --limit ${NEW_HOST_NAME}
```

setup-everything will prepare the host as add-host used to and will install all the appropriate OpenStack services (both nova and neutron).

**Comment by robb-romans** [comment]
@stevelle thanks! revised: https://github.com/rpcdocs/rpcdocs/pull/56

**Comment by robb-romans** [comment]
that last bit of patch is for the v9 branch of our rpcdocs repo, since ye olde standalone v9 repo is now deprecated
