### ISSUE TITLE
Add configuring Glance to use NFS information to the v10 and v11 Installation Guide

### ISSUE THREAD

**Issue by darrenchan** [rpcdocs/docs-issues#77]
From Aaron Segura: 

Here's what's needed to use an NFS back-end with glance:

Make Directory for infra bare-metal mount:
/opt/os-ansible-deployment/rpc_deployment# ansible infra_hosts -m shell -a 'mkdir /mnt/glance_container_nfs'

Add NFS to fstab:
/opt/os-ansible-deployment/rpc_deployment# ansible infra_hosts -m shell -a 'echo X.X.X.X:/MNT /mnt/glance_container_nfs nfs nfsvers=3,rsize=32768,wsize=32768,actimeo=0,retry=120,hard 0 0 >> /etc/fstab'

Mount it up:
/opt/os-ansible-deployment/rpc_deployment# ansible infra_hosts -m shell -a 'mount -a'

Verify:
/opt/os-ansible-deployment/rpc_deployment# ansible infra_hosts -m shell -a 'mount | grep nfs'

Add line to lxc config for glance containers:
/opt/os-ansible-deployment/rpc_deployment# ansible infra_hosts -m shell -a 'echo lxc.mount.entry = /mnt/glance_container_nfs/ var/lib/glance/images none defaults,bind,rw 0 0 >> /var/lib/lxc/$(lxc-ls | grep glance_container)/config'

Restart glance containers:
/opt/os-ansible-deployment/rpc_deployment# ansible infra_hosts -m shell -a 'lxc-stop -n $(lxc-ls | grep glance_container)'
/opt/os-ansible-deployment/rpc_deployment# ansible infra_hosts -m shell -a 'lxc-start -d -n $(lxc-ls | grep glance_container)'

**Comment by darrenchan** [comment]
@toxick  can you review https://github.com/rpcdocs/v10/pull/277. Thanks.

For v11 (Kilo), since /opt/os-ansible-deployment/rpc_deployment directory no longer exists, where  would you create the mount directory?

**Comment by toxick** [comment]
The mount directory would be the same @ /mnt/glance_container_nfs, but you would run all of the commands from whatever replaces the rpc_deployment directory.  I think it's /opt/os-ansible-deployment/openstack_deployment/ maybe?

**Comment by darrenchan** [comment]
Thanks @toxick, I believe it's  /opt/os-ansible-deployment/openstack_deploy.
Btw can you review rpcdocs/v10#277 and rpcdocs/rpcdocs/pull/60 and let me know of any changes?

**Comment by BjoernT** [comment]
Can we please add the information that the package nfs-common needs to be installed prior to the configuration on all infra nodes ?

**Comment by klevenstein** [comment]
Reopening.

**Comment by robb-romans** [comment]
@BjoernT OK to close?

**Comment by BjoernT** [comment]
@robb-romans  If we added the nfs-common package, then we are ok to close it

**Comment by robb-romans** [comment]
@BjoernT thanks
