### ISSUE TITLE
Kilo Documentation Changes

### ISSUE THREAD

**Issue by pmesserli** [rpcdocs/docs-issues#78]
There were a number of changes that we had in our etherpad while QC'ing the release.  I've included some items that we noticed below.  This had applied to the bk-rpc-installation-internal-20150427.pdf at the time.
Page 14 : snet interface eth4 is typically not eth4, just remove this hint
Page 63: Playbook name is missing under step 2 for removing haproxy
Page 72: Under Note: Entities can be created via https://si.rackspace.com/MaaS/MaaSPanel.aspx if you do not have access you can contact the SI team to grant access. You do not need to email the asops team to create the entries.

**Comment by robb-romans** [comment]
@pmesserli does this fix look ok?

**Comment by robb-romans** [comment]
closing. reopen if needed.
