### ISSUE TITLE
Add step to the documentation for user_secrets.yml file

### ISSUE THREAD

**Issue by claco** [rpcdocs/docs-issues#79]
This is part code/part documentation. Security has asked that we tweak the file permissions of the user.secrets.yml file, or optional, have folks use ansible-vault to encrypt/decrypt it so it is not in the clear.

Most of this I think would be additions to the installation steps covered in the OSAD README and in the RPC installation guide itself.

The upstream bug: https://bugs.launchpad.net/openstack-ansible/+bug/1461997

**Comment by robb-romans** [comment]
@ionosphere80 are you still working on this?

**Comment by ionosphere80** [comment]
I don't think we need to update any RPC documentation for this change.
