### ISSUE TITLE
Juno: Documentation -- Icehouse to Juno Upgrade

### ISSUE THREAD

**Issue by sigmavirus24** [rpcdocs/docs-issues#8]
Originally created by @b3rnard0 on 2014-11-13 03:19:27+00:00
----
Document the upgrade process from Icehouse to Juno.

NOT for the 10/16 release

- [x] Update the installation guide
- [x] Update the release notes
- [x] Update the Knowledge Center pages
- [x] Verify builds on docs.rackspace.com

**Comment by klevenstein** [comment]
Released for v10 GA
