### ISSUE TITLE
How to override nova_console_endpoint

### ISSUE THREAD

**Issue by jklint** [rpcdocs/docs-issues#83]
Customer requires a change to the URL presented when accessing an instance's console via Horizon (or `nova get-spice-console`). Currently this defaults to the public VIP. It appears that nova_console_endpoint is the variable to override, but I am unsure of which playbooks are needed to be run in order for the change to take affect.

**Comment by klevenstein** [comment]
@cloudnull @nrb @mancdaz any further insight into this?

**Comment by nrb** [comment]
@jklint What version are you using? I'm assuming a Juno release since you're referring to a customer?

**Comment by nrb** [comment]
@jklint To answer your question - in Kilo and Juno you'd run the nova playbooks to reconfigure this.

Ok, so looking at current current HEAD of Kilo, I found this:

The public VIP is used in building up the HTML5 proxy var (`nova_spice_html5proxy_base_url`) [here](https://github.com/stackforge/os-ansible-deployment/blob/kilo/playbooks/roles/os_nova/defaults/main.yml#L153)

`nova_spice_html5proxy_base_url` is then set in nova.conf, [here](https://github.com/stackforge/os-ansible-deployment/blob/kilo/playbooks/roles/os_nova/templates/nova.conf.j2#L115).

In Juno, the `nova_console_endpoint` variable was used, as seen [here](https://github.com/stackforge/os-ansible-deployment/blob/juno/rpc_deployment/vars/openstack_service_vars/nova_spice_console_endpoint.yml#L16), and set in [nova.conf](https://github.com/stackforge/os-ansible-deployment/blob/juno/rpc_deployment/vars/openstack_service_vars/nova_spice_console_endpoint.yml#L16).

So, for Kilo, it looks like we may have a regression - the `nova_console_endpoint` var is not even used in the construction of the final URL.  In both cases, you should be able to set the value in the appropriate `user_variables.yml` file and re-run the nova playbooks.

**Comment by robb-romans** [comment]
per @nrb this variable is NFG in v11. fix to follow later. OK for v10/Juno.

**Comment by nrb** [comment]
I filed a bug upstream, https://bugs.launchpad.net/openstack-ansible/+bug/1477747

**Comment by robb-romans** [comment]
@nrb @RobinJoe @jklint Looks like the upstream bug was marked invalid. With the above doc changes, can this issue be closed? Thanks.
