### ISSUE TITLE
Kilo/master: document the required repo-infra_hosts group

### ISSUE THREAD

**Issue by nrb** [rpcdocs/docs-issues#84]
For Kilo+, the ``repo-infra_hosts`` group or the ``openstack_repo_url`` variable is required.

I have created an [upstream bug](https://bugs.launchpad.net/openstack-ansible/+bug/1475000) for the in-tree install guide, and uploaded [a patch](https://review.openstack.org/#/c/202258/) for the change to the ReST documentation.

**Comment by darrenchan** [comment]
Fix from @ionosphere80:  https://github.com/rpcdocs/rpcdocs/pull/136
