### ISSUE TITLE
Overriding resume_guests_state_on_host_boot

### ISSUE THREAD

**Issue by jklint** [rpcdocs/docs-issues#85]
I have customer running 10.1.10 that wishes to enable the setting resume_guests_state_on_host_boot in nova. Grepping through the playbooks I can't seem to find any reference. Can this variable be set, and what are the steps to do so?

**Comment by nrb** [comment]
I don't see a reference in https://github.com/stackforge/os-ansible-deployment/blob/juno/rpc_deployment/roles/nova_common/templates/nova.conf to it, so I don't think it's likely that it can be changed with OSAD variables right now.

**Comment by nrb** [comment]
Yeah, according to http://docs.openstack.org/juno/config-reference/content/list-of-compute-config-options.html, this option is set in nova.conf, and right now it's not exposed in OSAD.

**Comment by robb-romans** [comment]
Thanks @nrb
