### ISSUE TITLE
`nova-manage db null_instance_uuid_scan` does not exist in Juno

### ISSUE THREAD

**Issue by byronmccollum** [rpcdocs/docs-issues#91]
RPC v11 Release Notes, 2015/08/18 Build, 4. Upgrading, Prerequisites: The command `nova-manage db null_instance_uuid_scan` does not exist in Juno. This command was added in Kilo, and would not be available to run as a prerequisite until after the upgrade has completed.

Should this be a post-install task instead?

**Comment by ionosphere80** [comment]
I opened this in the rpcdocs repo because it impacts not-yet-official documentation.

https://github.com/rpcdocs/rpcdocs/issues/237

**Comment by klevenstein** [comment]
Fixed, closing.
