### ISSUE TITLE
Update all docs for stackforge/os-ansible-deployment -> openstack/openstack-ansible

### ISSUE THREAD

**Issue by robb-romans** [rpcdocs/docs-issues#93]
Issue: Update OSAD naming and paths in all docs.

NB: This adds some work and an additional external dependency to the docs releases. If the RPC v11 release occurs before this change on 11 Sept., we will have to update all those docs again after the release.

From Jesse:

The namespace move and repository rename of stackforge/os-ansible-deployment to openstack/openstack-ansible has finally been scheduled for Friday, 11 September 2015. For reference, the review is https://review.openstack.org/#/c/200730/

Note that this will affect all branches including juno, kilo and master. This will likely also affect rpc-openstack.

Please be prepared to adjust documentation, blogs, code, etc to reflect the new repository location. I would also suggest arranging to rename any summit presentation references to OSAD (and other derivatives) to rather refer to ‘openstack-ansible’.

From Kevin:

This will affect all branches. Infra is in the process of making stackforge go away so while governance approved the move for only kilo / master infra will be bringing over all of the branches.

**Comment by klevenstein** [comment]
List of affected files from an `ack` command (minus the HTML target output):

```
rpc-common/common-front.xml
rpc-installation/src/docbkx/app-osad-configfiles.xml
rpc-installation/src/docbkx/app_recover_galera_cluster.xml
rpc-installation/src/docbkx/ch-configure.xml
rpc-installation/src/docbkx/ch-hosts-deployment.xml
rpc-installation/src/docbkx/ch-hosts-target.xml
rpc-installation/src/docbkx/ch-operations.xml
rpc-installation/src/docbkx/ch-overview.xml
rpc-installation/src/docbkx/ch-playbooks-foundation.xml
rpc-installation/src/docbkx/ch-playbooks-infrastructure.xml
rpc-installation/src/docbkx/ch-playbooks-openstack.xml
rpc-installation/src/docbkx/ch-playbooks-rpc.xml
rpc-installation/src/docbkx/swift/sec-object-storage-existing-kilo.xml
rpc-installation/src/docbkx/swift/sec-object-storage-image-service.xml
rpc-installation/target/docbkx/bk-rpc-installation.xml
rpc-ops/src/docbkx/ch-compute.xml
rpc-ops/src/docbkx/ch-containers.xml
rpc-ops/src/docbkx/ch-upgrade.xml
rpc-ops/target/docbkx/bk-rpc-ops.xml
rpc-releasenotes/target/docbkx/bk-rpc-releasenotes.xml
rpc-swift/src/docbkx/app-object-storage-configfiles.xml
rpc-swift/src/docbkx/ch-object-storage-playbook.xml
rpc-swift/src/docbkx/ch-object-storage-stand-alone.xml
rpc-swift/target/docbkx/bk-rpc-swift.xml
rpc-v9-releasenotes/target/docbkx/bk-rpc-releasenotes.xml
```

**Comment by klevenstein** [comment]
@darrenchan Let's add the following note to the release notes under What's New:

> **Repository rename**  
> As of 11 September 2015, the repository `stackforge/os-ansible-deployment` has been renamed to `openstack/openstack-ansible`. The documentation has been updated accordingly.

Or something to that effect; feel free to develop more elegant wording.

**Comment by robb-romans** [comment]
@klevenstein I'll add that blurb

**Comment by klevenstein** [comment]
Per discussion on IRC: the upstream change is scheduled to happen between 2300 and 2330 UTC on Friday (6PM US Central).

Repo move patch: https://review.openstack.org/#/c/200730/

**Comment by klevenstein** [comment]
We'll be coordinating the publishing update with @steveortiz on Friday evening.
