### ISSUE TITLE
Document 'is_metal' flag

### ISSUE THREAD

**Issue by ionosphere80** [rpcdocs/docs-issues#94]
Document 'is_metal' flag in /etc/rpc_deploy/rpc_environment.yml file. In particular, enabling it by default for nova compute and swift storage containers along with the recommendation to enable it for cinder volume if the deployment uses the LVM-iSCSI driver.

**Comment by BjoernT** [comment]
I think we have this documented already

**Comment by klevenstein** [comment]
This is a Juno bug, yes?

**Comment by BjoernT** [comment]
This is for kilo only, especially the cinder part IMHO

**Comment by ionosphere80** [comment]
We should deploy cinder with the LVM-iSCSI driver on bare metal in all releases. This flag defaults to 'true' in Kilo, but not in Juno.

**Comment by darrenchan** [comment]
Issue is duplicated in https://github.com/rpcdocs/rpcdocs/issues/268

**Comment by asettle** [comment]
This has definitely been done now. Closing, thank you.
