### ISSUE TITLE
Horizon Certificate Upgrade Step from v10 to v11

### ISSUE THREAD

**Issue by sigmavirus24** [rpcdocs/docs-issues#98]
In the section for dealing with [Horizon's Certificates from v10 to v11](http://docs-internal-staging.rackspace.com/rpc/api/v11/bk-rpc-ops/content/horizon-self-signed-certs.html) we have steps for dealing with new defaults in OpenStack Ansible Deployment v11. Following is some background that will hopefully make everything clearer.

# Background

In v10 of OSA, the Horizon playbooks would generate a OpenSSL Key and Certificate for Apache to use when serving Horizon. The variables in v10 were named `horizon_ssl_cert`, `horizon_ssl_key`, `horizon_ssl_cert_path`. These defaulted to (respectively) `/etc/ssl/certs/apache.cert`, `/etc/ssl/private/apache.key`, `/etc/ssl/certs`. Any install that wasn't manually changed/updated, will be using those values.

In v11 of OSA, the defaults for `horizon_ssl_cert` and `horizon_ssl_key` were changed, `horizon_ssl_cert_path` was removed, and [these new variables](https://github.com/openstack/openstack-ansible/blob/c110786e1f13c1f1758d280f6e69d4bcec5d7cc6/playbooks/roles/os_horizon/defaults/main.yml#L66..L75) were added.

Most of this bug applies to *pre-upgrade* steps (as implied (hopefully) by the link above).

# Upgrade scenarios

1. You were using the defaults from v10 with a self-signed certificate and want to continue using that certificate
1. You were using your own certificate, key, etc. but that was put in place by hand (either by a support team member or your own administrator)
1. You were using the defaults but would like to change something about them
1. The customer upgrades and some users browsers are too old to connect to Horizon

## Scenario 1 (Defaults upgrading using the old bits)

There are two different ways to maintain this:

1. Rename the old files

   ```
   # cd /opt/os-ansible-deployment/rpc_deployment  # or /opt/openstack-ansible/rpc_deployment
   # ansible horizon_all -m shell -a 'mv /etc/ssl/certs/apache.cert /etc/ssl/private/horizon.pem'
   # ansible horizon_all -m shell -a 'mv /etc/ssl/private/apache.key /etc/ssl/private/horizon.key'
   ```

1. **OR** Update `/etc/rpc_deploy/user_variables.yml` to add

   ```yaml
   horizon_ssl_cert: /etc/ssl/certs/apache.cert
   horizon_ssl_key: /etc/ssl/private/apache.key
   ```

   What I'm a little unclear about is where `horizon_ssl_ca_cert` comes into play

*Do not do both*

## Scenario 2 (Using your own key and certificate)

Simply use the `horizon_user_ssl_cert`, `horizon_user_ssl_key`, `horizon_user_ca_cert` variables in `/etc/rpc_deploy/user_variables.yml` and these will override any self-signed certificates in version 11.

## Scenario 3 (Regenerating self-signed certificates)

This has a couple different sub-scenarios:

1. Using the old paths but regenerating the the certificates, in that case, set the variables from `Scenario 1, option 1` and add (to `/etc/rpc_deploy/user_variables.yml`):

   ```yaml
   horizon_ssl_self_signed_regen: true
   ```

   At this point, you can also change the subject of the cert with

   ```yaml
   horizon_ssl_self_signed_subject: "..."
   ```

2. You don't care where the certificate lives, in this case, you don't need to set any variables at all because the old `apache.cert`, `apache.key` will be left there, and new keys, certificates, etc. will be placed in the new defaults. It will be regenerated due to the fact that the files don't exist where the new defaults expect them to be.

## Scenario 4 (Users are unable to connect to Horizon with very old browser versions)

Two of the [new variables](https://github.com/openstack/openstack-ansible/blob/c110786e1f13c1f1758d280f6e69d4bcec5d7cc6/playbooks/roles/os_horizon/defaults/main.yml#L66..L75) affect customers using much older browsers (e.g., Internet Explorer 6 or older):

- `horizon_ssl_protocol`
- `horizon_ssl_cipher_suite`

By default both v10 and v11 disable `SSLv2` and `SSLv3` in the protocol lists for Horizon, so no modification should be necessary there.

There is a difference between the cipher suites. The cipher suite as it [currently is set for Horizon in v10](https://github.com/openstack/openstack-ansible/blob/ff9209b47c6d93dad717b99b399d3b201bfdd07c/rpc_deployment/roles/horizon_apache/templates/openstack-dashboard.conf#L23) is

```
EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !RC4
```

In [v11](https://github.com/openstack/openstack-ansible/blob/c110786e1f13c1f1758d280f6e69d4bcec5d7cc6/etc/openstack_deploy/user_variables.yml#L109) it is

```
ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
```

Given that the new cipher suite list is meant to provide the best transport security, it is not advisable to reset the list to the previous default in v11. If users complain, however, that they are unable to connect it is plausible that the v11 defaults are causing connection issues. At that point, updating `user_variables.yml` (this would be post-upgrade and so the file would be `/etc/openstack_deploy/user_variables.yml`) to include only the cipher suites necessary would be okay followed by re-running the `os-horizon.yml` playbook from `/opt/rpc-openstack/openstack-ansible/playbooks` directory.

**Comment by robb-romans** [comment]
Fantastic, thanks @sigmavirus24

**Comment by odyssey4me** [comment]
``horizon_ssl_ca_cert`` should be the path to the ca cert which would have been placed in ``horizon_ssl_cert_path`` (I guess) by the deployer if they were using a real cert. The ca cert name could be anyone's guess - this is why the configuration was made to be more explicit, especially since testing with just placing the ca cert in the path didn't work in my testing.

**Comment by sigmavirus24** [comment]
> It might be better to suggest adding -e 'horizon_ssl_self_signed_regen: True' to the openstack-ansible command-line when wanting to regen the cert. Otherwise the deployer may unwittingly regen the cert every time they run the playbooks as they've forgotten it in the user_variables file.

It might, but we're suggesting this as a pre-upgrade step because the upgrade.sh script doesn't allow for that kind of option passing (nor does OSA's run-upgrade.sh script). If we cover the regen scenario, a note should be added to remove the line (or comment it out) after running the upgrade.

**Comment by odyssey4me** [comment]
If they wish to regen the certs then they can simply leave everything alone as the regen happens automatically with the default settings due to the lack of the target's cert file presence. :)

**Comment by robb-romans** [comment]
https://review.openstack.org/#/c/224980/

**Comment by robb-romans** [comment]
@odyssey4me @sigmavirus24 @klevenstein please review https://github.com/rpcdocs/rpcdocs/pull/329

Thanks!
