### ISSUE TITLE
[Upgrades] v10 to v11 Keystone Apache Configuration

### ISSUE THREAD

**Issue by sigmavirus24** [rpcdocs/docs-issues#99]
In upgrading from v10.1.14 to r11.0.0 of rpc-openstack this morning, the team ran into [this bug report](https://github.com/rcbops/rpc-openstack/issues/339). This should have been fixed in upstream OSA but the fix is incorrect. To avoid this, the users will need to insert into their users variables **pre-upgrade** the following:

```yaml
# In /etc/rpc_deploy/user_variables.yml
keystone_wsgi_threads: 1
```

This will override the default number of threads which is calculated to be half the number of VCPUs.

We're testing this to ensure this behaves as expected.

**Comment by odyssey4me** [comment]
That will likely work, but seems more like a workaround than an actual solution for the root cause.

**Comment by sigmavirus24** [comment]
@odyssey4me so this isn't the place to discuss the actual problem, but let me give you the cliff notes.

- Apache + mod_wsgi uses a concept in Python called "sub-interpreters", these are written by using Python's C-API and doing very bizarre things to the Global Interpreter Lock.
- Many things in OpenStack rely on Global State. For example, the `ArgsAlreadyParsedError` is because Keystone has a `CONF` object and it tries to register arguments after having already registered those arguments (e.g., trying to register `--config` twice).
- Because of subinterpreters, the global state is set, but then the same code is re-executed with the same global state in place causing errors

For `cryptography` the problem is that they don't allow you to do bad things (like registering `osurandom` more than once because you're registering it to the OpenSSL backend) and for `oslo.config`, it doesn't let you re-register configuration options (because there's no reason to re-register something or to fail silently).

Sub-interpreters specifically come into play when you're using threads in Apache. By setting those to 1, you will not see this. Keeping processes where it is, is perfectly fine because Python handles global state being sent to sub-processes perfectly fine. It's a different execution path.

Since we have no control over sub-interpreters, and the Python Cryptographic Authority are working hard on fixing this appropriately for Apache, the best solution is this. Further, since the fix doesn't rely on *only* a fix in cryptography but also (at **least**) oslo.config, this is not immediately something that can be fixed by deployers outside of what would likely be some really awful patches to those libraries and code bases directly. This is *absolutely* the best fix as a deployer.

**Comment by nrb** [comment]
I would think this also affects new deployments, too, since it's really applying the defaults found in the roles, not modifying anything during the upgrade process.

**Comment by odyssey4me** [comment]
@nrb Agreed, this will most definitely affect all deployments.

**Comment by odyssey4me** [comment]
Thanks for the explanation @sigmavirus24 - I've filed https://review.openstack.org/225145 to resolve this upstream, but the override can also be used as you've already noted.
